version: "3.8"
services: 
    web:
        build: .
        ports:
            - "3000:3000"
    sql:
        image: "crate:latest"
        volumes:
            - ./data:/data
        ports:
            - "4200:4200"